### ISSUE TITLE
Table name pluralization -- similar to Mongoose

### ISSUE THREAD

**Issue by oprearocks** [dynamoosejs/dynamoose#134]
I've been migrating from MongoDB + Mongoose to DynamoDB and I really appreciate the things this module does. I managed to do an almost seamless migration, with very little modification. One thing I'm missing in dynamoose is the default collection name pluralization Mongoose offered. 

As far as most of the AWS DynamoDB training materials, tutorials and articles go, they all suggest using plural form for table names.  Would you consider introducing such functionality in the library? 

If this sounds like a useful feature, I could go ahead and add a pull request to introduce it. I already went through the mongoose repository and found the functionality which adds the plural form for MongoDB collection names.

The details are here: https://github.com/Automattic/mongoose/blob/master/lib/utils.js#L23

Adrian.

**Comment by opreaadrian** [comment]
There is also the option of using the pluralize module on npm -- https://www.npmjs.com/package/pluralize. Looks like it has a decent amount of downloads.

**Comment by brandongoode** [comment]
Sounds like a great addition.  Please make sure it defaults to the current behavior and has an option for pluralizing.  Also, add a couple test cases and document the option in the Readme.

Thanks

**Comment by opreaadrian** [comment]
Sure thing! I will look into it and add everything you requested.

**Comment by opreaadrian** [comment]
As far as I can see, Mongoose will drop pluralization in their next breaking change release. 
As per https://github.com/Automattic/mongoose/issues/5209 and https://github.com/Automattic/mongoose/issues/1350 they plan on "killing it with fire". 
How about we start a discussion and get more people to talk around this. 

As far as I'm concerned, I only raised the issue because I was accustomed with the workflow from Mongoose. On the other hand, I see that some people disagree with this, and I would like to take the pulse of this community and see how people feel about this. 

Cheers!

**Comment by brandongoode** [comment]
I'm still fine with having it as an option, but don't want it to be the default behavior.

**Comment by opreaadrian** [comment]
That's better. I would have instinctively added it to the default behavior, just like Mongoose. So it will be opt-in rather than opt-out, like in the case of Mongoose. 

Then, it will be an option of the `dynamoose#model()` function.

**Comment by brandongoode** [comment]
Yes, sounds great.  It could also be set with `dynamoose.setDefaults` once and passed to all models.

**Comment by opreaadrian** [comment]
Thanks for the heads-up. I'll keep that in mind.

**Comment by lrcry** [comment]
I think we can specify any table name when we define the schema/model.

```
dynamoose.model('any-tablename-you-want', ...);
```

**Comment by fishcharlie** [comment]
@oprearocks You interested in creating a PR for this?

**Comment by fishcharlie** [comment]
Due to the fact that this issue is very inactive, and mongoose dropped it a release. I'm closing this issue for now. I'm totally open to integrating it into the library, so long as it's not a breaking change, and the default remains the same as what it is now.

If anyone wants to take that on, feel free to submit a PR.
