### ISSUE TITLE
Attributes are deleted when empty string passed as value even when required: true

### ISSUE THREAD

**Issue by jderose9** [dynamoosejs/dynamoose#155]
If I set an attribute in a schema to be required, set it to '' in the model, and then call .save(), the save fails due to the field being required (this makes sense to me).

If I pass that key with a value of '' to .update() it will success and delete the attribute from the document. The logic is that if the value is null, undefined, or '' then a delete operation is added to the update expression. I think that this update should be rejected since the field now no longer exists despite being required in the schema.

I've tried to work around this with a validation function that checks for empty string, however it seems that the validation doesn't run on empty strings (presumably because they will be deleted).

**Comment by brandongoode** [comment]
@jderose9 thanks for reporting the inconsistent behavior.

**Comment by fishcharlie** [comment]
This is due to the following section of code:

https://github.com/dynamoosejs/dynamoose/blob/61e27104e3ca8fafac76003bd06c637af98599b0/lib/Model.js#L994-L1024

Since the default of that option is false. So unless you override that option to true, it will never do the required check.

I think the solution might be to split up the required and default logic. So we check for if it's required regardless of `options.createRequired`, and we handle the default logic if `options.createRequired` is set to true.

Might also be worth renaming that option.

I think no matter what this is a breaking change, and we should wait for a major version to deploy this.

@brandongoode thoughts?

---

I guess one other idea is to separate the logic from that, and check to see the property is a required property in the schema here:

https://github.com/dynamoosejs/dynamoose/blob/61e27104e3ca8fafac76003bd06c637af98599b0/lib/Model.js#L811-L815

**Comment by fishcharlie** [comment]
I think that last option will work. I wrote an example for it. Just have to clean up the code quite a bit, and submit a PR for it.
