### ISSUE TITLE
how to do error handling while connecting  to dynamodb using dynamoose

### ISSUE THREAD

**Issue by venkataprasadmanne** [dynamoosejs/dynamoose#407]
I need help.I am looking for a code similar to mongoose like below to do error handling while starting the app.
it seems this is not supported in dynamoose as of now.is there any alternate approach? 
because there is no point in going further continuing with starting app while database connection failed.so i just want to add a check

```
require ( 'dynamoose' ).connection.on ( 'error' , function () {
    console.log(  'A database error occurred, closing the app'  );
    process.exit ( 1 );
} );

require ( 'dynamoose' ).connection.once ( 'open' , function () {
    console.log ( 'Database is open.' ) ;

//logic for intiating application

} );

```

**Comment by fishcharlie** [comment]
@venkataprasadmanne Due to how Dynamoose is setup this is not supported and I don't see it being supported anytime soon.

Unlike most database systems AWS DynamoDB doesn't use a persistent connection to the database. There is no such thing as opening a connection to the database and closing the connection (unlike MySQL, MongoDB, etc).

In order to handle errors in Dynamoose, I would just do all your error handling code within the actual database commands. Although I do know there are certain cases where Dynamoose will throw errors outside of commands that you have run. This is mainly when you `require` your models, and if there is an error verifying that the database is active, or creating the database. Of course you can disable both of those options to not throw errors in those cases and handle those manually. There might be other cases, but I'm unaware of such cases.

**Comment by venkataprasadmanne** [comment]
@fishcharlie Thanks for the help! I got it
