### ISSUE TITLE
Double sorting

### ISSUE THREAD

**Issue by Nikhil2508** [dynamoosejs/dynamoose#416]
I would like to Double sort using bidAmount and userCount in ascending order using following schema: 

const bidsFrequencySchema = new Schema({
  auctionId: {
    type: Number,
    hashKey: true
  },
  bidAmount: {
    type: Number,
    validate: function (v) {
      return validations.validBidAmount(v);
    },
    rangeKey: true
  },
  userId: {
    type: Array
  },
  userCount: {
    type: Number,
    index: true
  }
},
  {
    timestamps: true,
  }
);

Below query doesnt work: 

 await bidsFrequencyModel.query({ auctionId: auctionId }).where('userCount, bidAmount').ascending().limit(1).exec();

Please help.

**Comment by fishcharlie** [comment]
@Nikhil2508 We strongly encourage issues and PRs to follow the template that is provided when you create an issue or PR. This is because it gives us a lot of information we need in order to help. Because you did not do that is makes it a lot more difficult for us to help. The statement “Below query doesnt work” is very broad and doesn’t give any detail about why it doesn’t work. Is it throwing an error? Is it failing silently? What do you expect to be returned? What is being returned? Do you have code for your model that you can show us? Why do you expect that “where” code with two property names separated by a comma to work? Did you find that in the documentation? It’s also helpful for us to know what environment you are working in. Are you running the latest version of Dynamoose? Is this a feature request or do you have reason to believe this is a current bug in Dynamoose or just a question?

I will be closing this issue for now. But will consider reopening if the correct details and structure is followed.
