### ISSUE TITLE
Highest limit for number of records for one  dynamoose batchPut request

### ISSUE THREAD

**Issue by venkataprasadmanne** [dynamoosejs/dynamoose#433]
i am working to migrate data to dynamodb and there are around 20,000 records(each record is a simple JSON with around 10 fields) i need to insert in a table.I see that dynamoose has batchPut method for batch insertions and I am wondering  maximum how many records I can push for one batchput request? I see from dynamodb docs that  one dynamodb batchInsert  request would accept at max 25 records.

I am very new to both dynamodb and dynamoose ,could you please help me with the below?

(1)I have written a script in node js to loop through the 20,000 records and make one batchPut request for 25 records ,which means I would be making 800 batchPut requests .

(2)do I need to increase table throughout before running the script? increasing throughput to 100 write operations per second would be enough?

(3)if any batchPut operation fails then does dynamoose retry the operation? or do I need to explicitly code to retry if any operation fails?

(4) I want to test the script in my local  which has dynamodb.local  set up before running it on prod,can dynamodb.local can handle such huge number of insertions? is dynamodb.local performance equivalent dynamodb?

**Comment by fishcharlie** [comment]
Hi @venkataprasadmanne! You are correct that AWS has a limit for batchPut. I forget what that exact limit is, but 25 sounds correct.

So yes you will have to make 800 batchPut requests or so.

You will need to increase the table throughput in order to achieve this probably. The throughput is also dependent on the size of each document. So without knowing the size of your data I’m unable to give advice on how much to increase it to.

I’m PRETTY confident Dynamoose does retry the operation but I could be wrong. Dynamoose can still throw errors tho. So yes, you will have to explicitly write error handling code based on errors that you get back from Dynamoose.

If you let me know the size of your data I’d be more than happy to help with the throughput question further.

Good luck, and please don’t hesitate to reach out again if you have any further questions!!

**Comment by venkataprasadmanne** [comment]
@fishcharlie Thanks for the response.My each record is around 350 to 400 bytes ,could you pls suggest on throughput? I  looped through all the records and output to console to check if Node is able to handle this huge data  before writing the script  and it seems Node does  pretty well for for this data

**Comment by fishcharlie** [comment]
@venkataprasadmanne Ok so I'd suggest reading [this AWS page](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ProvisionedThroughput.html) for details on throughput.

The biggest unknown is how fast Node.js and Dynamoose is gonna be able to write these items. I think that might depend on your network connection and just speed of things overall.

If you are writing 20k items, and you want to do it all in 1 second, you'd need 20k write capacity to do that.

Now I don't think it'd be that fast, but I could be wrong.

I would for sure do retry logic, and maybe write code to throttle the items being put into DynamoDB inside of the code that you write.

For example, if you set your write capacity to 100. Set it to only write 100 items per second in your Node.js code. You could get through your 20k items in just over 3 minutes then about, unless there is some other bottle neck (network speed, etc.).

But if I was in your position, I'd probably write throttling code on the client side based on the throughput you set. But of course you could not do that, set the throughput to something massive (ex. 20k), and then lower it after you are done so you don't continue to get charged. BUT I wouldn't do that if I was in your position because that seems higher risk in terms of cost.

Last suggestion I'd make is to review the AWS pricing and everything, and make sure you have a solid game plan before doing it in terms of cost. But it sounds like you are doing that so yeah. 😃 

Let me know if you have any other questions!!

**Comment by fishcharlie** [comment]
I'm closing this for now, but if you still have questions @venkataprasadmanne please feel free to comment again and I can help further.

**Comment by venkataprasadmanne** [comment]
@fishcharlie your idea of throttling code on the client side based on the throughput is a  really great.I will try that and let you know.

**Comment by venkataprasadmanne** [comment]
@fishcharlie I tried the throttling code to make one batchPut request for each 3 seconds and although my script took around 40 mins to finish all batchPut requests it went pretty smooth without  error and data is pushed successfully.I would have been in a real mess had I tried the idea of  increasing the throughput and dumped all thousands of request onto dynamo db in few milliseconds even while considering that i would set the throughput very high.Thanks to your suggestion.I am able to do this without altering my throughput much and duration for run time of the script doesn't matter here  as its one time activity and safe migration is only criteria.i really appreciate your help in this

**Comment by fishcharlie** [comment]
@venkataprasadmanne I'm so glad it worked out well for you!! Please feel free to contact me or create more issues if you ever have problems or questions about Dynamoose in the future. Best of luck in your future coding projects!

**Comment by kisanme** [comment]
Isn't it possible for the Dynamoose library to implement something like https://github.com/awslabs/dynamodb-data-mapper-js#batch-operations

> The mapper also supports batch operations. Under the hood, the batch will automatically be split into chunks that fall within DynamoDB's limits (25 for batchPut and batchDelete, 100 for batchGet). The items can belong to any number of tables, and exponential backoff for unprocessed items is handled automatically.

**Comment by fishcharlie** [comment]
@kisanme This needs more detail. What specifically are you asking about? If we can use that library to achieve that goal? Or if we can implement that same thing?

Please create a new issue or discussion with more detail here.
