### ISSUE TITLE
Why am i not able to use save and put function from model

### ISSUE THREAD

**Issue by AbhijetPokhrel** [dynamoosejs/dynamoose#441]
I am using dynamoose v 1.0.0 and according to the documentation I can use save and put function in the model. But when I use them, they are undefined. However batchput function is working.

Am I missing anything?

**Comment by fishcharlie** [comment]
Hi @AbhijetPokhrel. We use GitHub issue and PR templates so that we can easily get all of the information needed to debug the issue. For example, showing your model and schema code, along with the code you are trying to use for the save and put functions would be supeer helpful in this situation.

Also, have you tried this in other versions of Dynamoose successfully? Is it just a v1.0 issue or does it happen in other versions?

Any additional information you can provide to help us debug would be helpful as well.

I'm closing this issue for now. Please feel free to submit a new issue with all of the information in the template so we can work to debug it and help fix it.
