### ISSUE TITLE
Dynamoose Performance Issues

### ISSUE THREAD

**Issue by Nikhil2508** [dynamoosejs/dynamoose#458]
### Summary:
I am trying to compare dynamodb native and dynamoose performance. I ran a test of 500vU per second via jmeter. I am running an ec2 instance c5xL with amazon linux. I am seeing a huge latency when I perform the same test with dynamoose. Also the throughput achieved with dynamoose is quite low than that with native dynamodb connection (AWS-SDK). I have attached the test results screenshots in the
 
![500cuwithroutingwithdynamoose](https://user-images.githubusercontent.com/17094507/48543435-8918e680-e8e7-11e8-8627-02dbfdb224b9.PNG)
![500cuwithroutingwithoutdynamoose](https://user-images.githubusercontent.com/17094507/48543436-89b17d00-e8e7-11e8-90d9-ea0d3a2b90a6.PNG)

Please help me as I have to use dynamoose but if it cannot give me proper throughput for high concurrency I might not be able to use it as my app is application is going to have very high concurrency requirement.

Operating System:
Operating System Version:
Node.js version (`node -v`): 10.8.0
NPM version: (`npm -v`): 6.2.0
Dynamoose version:  0.8.7

### Other information (if applicable):
If I am not clear in explaining my problem pls let me know in the comments.

### Type (select 1):
- [x] Question

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have filled out all fields above
- [ ] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
Oh man, that isn't good at all. I expect Dynamoose to be slower than AWS SDK directly since it is doing more work, but I think we can work to improve those numbers. I don't think it should be that bad.

Few things. First I would read issue #327. That `describeTable` call can slow things down. So I would verify that is all correct.

Second, I would try to run `export DEBUG=dynamoose*` and run it again and see if that produces anything interesting or if anything looks odd in that.

Third, what operation are you running? And is this specific to one type of Dynamoose operation? Or is it a consistent thing across all of the Dynamoose operations?

Finally, I would maybe test adding in some logs or something into Dynamoose directly and see where the slow down is happening. Without pin pointing where the cause of this is, it's hard for me to really give a lot of advice or fix things.

I wanna make sure Dynamoose is the best possible package for you, so I look forward to working with you to ensure we can get that performance to be better. Any additional information you can provide would be very helpful.

**Comment by fishcharlie** [comment]
@Nikhil2508 

> I will be attaching the x ray service to my dynamo and re run today. Also try the export options to check out what is going wrong.

Awesome! Let me know how that goes.

> Also I would like to know if you have done any benchmarking for this library in terms of how many concurrent connections can be achieved using this library on a single AWS instance.

I'm not sure what you mean by that. Remember, NoSQL database solutions are not like SQL database solutions. So the concept of a connection doesn't really exist in DynamoDB. In something like MySQL you have to connect and disconnect to the database server. That isn't the case for DynamoDB. So I'm really confused about what you mean by `concurrent connections`.

> Have you used this library for highly concurrent applications?

I personally I have not used Dynamoose at massive scale. That being said, this is the first time I've heard of performance issues with it. Remember, at the end of the day Dynamoose is built on top of AWS SDK, so the performance of AWS and the AWS SDK is a theoretical limit for Dynamoose performance. And I feel like knowing what I know about this library, we should be semi close to that limit. I'm surprised to see such massive differences between AWS SDK and Dynamoose. Which is why my first suggestion was to check the `describeTable` thing.

> I am sorry for all the trouble but I am very close to production deadlines and this can be a big issue for me. Any help from your end would be really helpful. Also if you would need anything from me do let me know.

No worries at all! I use this library in a **LOT** of the projects I work on. And someday I hope those projects scale. So I always try to make this library the best it can possibly be to ensure it works well for me as well, because there is a chance if people are having problems with Dynamoose, someday I might run into those same problems. So ensuring that this library works well for everyone is a high priority of mine.

Keep me posted on how things go.

Also, if you have any additional information you have that you would not like to share on this public form, please feel free to [contact me](https://charlie.fish/contact). From what it sounds like, that isn't the case yet, but just wanted to give that option.

**Comment by fishcharlie** [comment]
Few updates. This is for sure a problem with Dynamoose. I tested the following code snippets for AWS-SDK and Dynamoose.

- [Dynamoose test](https://gist.github.com/fishcharlie/5d5c284351a1e5a45108e44534c74d13)
- [AWS-SDK test](https://gist.github.com/fishcharlie/af416ea10984efdd9499e174bf13ef75)

For 10k records:

- Dynamoose took **256.616 seconds**
- AWS-SDK took **14.217 seconds**

For 1k records:

- Dynamoose took **5.089 seconds**
- AWS-SDK took **2.144 seconds**

Which to me, means the more items, the worse it gets. It's not just about 2x worse.

I have no idea what is going on here tho.

I did notice this when running `export DEBUG=*`:

```
  dynamoose:model put 1542865652228 Model-TestDB { id: '644', name: 'HelloDynamoose', ts: 1542865650860 } +2ms
  dynamoose:attribute toDynamo {"S":"644"} +0ms
  dynamoose:attribute toDynamo {"S":"HelloDynamoose"} +0ms
  dynamoose:attribute toDynamo {"N":"1542865650860"} +0ms
  dynamoose:schema toDynamo: [object Object] +0ms
  dynamoose:attribute parseDynamo: id : "string" : "644" +0ms
  dynamoose:attribute parseDynamo: name : "string" : "HelloDynamoose" +0ms
  dynamoose:attribute parseDynamo: ts : "number" : 1542865650860 +1ms
  dynamoose:schema parseDynamo: [object Object] +0ms
  dynamoose:model putItem 1542865652229 { TableName: 'TestDB',
  Item:
   { id: { S: '644' },
     name: { S: 'HelloDynamoose' },
     ts: { N: '1542865650860' } } } +0ms
  dynamoose:model put 1542865652230 Model-TestDB { id: '645', name: 'HelloDynamoose', ts: 1542865650860 } +1ms
  dynamoose:attribute toDynamo {"S":"645"} +0ms
  dynamoose:attribute toDynamo {"S":"HelloDynamoose"} +0ms
  dynamoose:attribute toDynamo {"N":"1542865650860"} +0ms
  dynamoose:schema toDynamo: [object Object] +0ms
  dynamoose:attribute parseDynamo: id : "string" : "645" +0ms
  dynamoose:attribute parseDynamo: name : "string" : "HelloDynamoose" +0ms
  dynamoose:attribute parseDynamo: ts : "number" : 1542865650860 +0ms
  dynamoose:schema parseDynamo: [object Object] +0ms
  dynamoose:model putItem 1542865652230 { TableName: 'TestDB',
  Item:
   { id: { S: '645' },
     name: { S: 'HelloDynamoose' },
     ts: { N: '1542865650860' } } } +0ms
```

Time time between the two put calls is about 2ms. Which compounds and adds up probably. I'm not sure exactly what could be causing this because it seems my code is pretty efficient. My only guess is that the size of the Dynamoose model instances are large enough to where it adds up to move those around. But not sure if that is accurate, or how we could improve that.

@brandongoode any thoughts here?

**Comment by fishcharlie** [comment]
Also related issue: #52.

Just ran some tests on an AWS instance as well and got the following results:

```
ubuntu@ip-123-45-67-890:~/tmp$ node aws.js 
Start time:  1542867377289
Promise created time:  1542867377293
Promise put created time:  1542867377726
End time:  1542867381931
Difference 4.642  seconds
ubuntu@ip-123-45-67-890:~/tmp$ node dynamoose.js 
Start time:  1542867385666
Promise created time:  1542867385671
Promise put created time:  1542867386178
End time:  1542867390308
Difference 4.642  seconds
ubuntu@ip-123-45-67-890:~/tmp$ node aws.js 
Start time:  1542867394278
Promise created time:  1542867394282
Promise put created time:  1542867394695
End time:  1542867398836
Difference 4.558  seconds
ubuntu@ip-123-45-67-890:~/tmp$ node dynamoose.js 
Start time:  1542867400429
Promise created time:  1542867400434
Promise put created time:  1542867400952
End time:  1542867405145
Difference 4.716  seconds
ubuntu@ip-123-45-67-890:~/tmp$ 
```

So it looks very similar between Dynamoose and AWS-SDK.

Also, not sure if this made a difference, but added the following lines as suggested in #52 to both AWS-SDK and Dynamoose.

```
	httpOptions: {
	  agent: new https.Agent({
		rejectUnauthorized: true,
		keepAlive: true
	  })
	}
```

**Comment by fishcharlie** [comment]
After talking to @Nikhil2508 more. It was determined that the latency is now working as expected between AWS-SDK and Dynamoose. Sounds like there are still problems with high CPU usage. According to @Nikhil2508 that is a problem with both Dynamoose and AWS-SDK. Therefore since this is not a Dynamoose specific issue, I’m closing this for now.

If anyone else has any problems with similar issues, please open a new issue, and tag this issue in your new issue.

I will continue to communicate with @Nikhil2508 offline and try to support with the high CPU utilization issue, and if any new developments come up I will post here.

Feel free to message me at anytime @Nikhil2508! 😃

**Comment by mogwai** [comment]
Was this issue resolved?

**Comment by fishcharlie** [comment]
@mogwai No code changes were made related to this issue directly. There was not enough information for me to reproduce this or resolve it. So if you have further information to provide to help debug this or fix it, that would be really helpful. But at this point I have not experienced this, and have no way to really debug it and therefore no way to improve it.

**Comment by aecorredor** [comment]
I know this issue was closed a while ago, but I just ran some load tests and saw the issue related to https://github.com/dynamoosejs/dynamoose/issues/327 with `describeTable`. I'll try turning that off. But, besides that, are the other issues that were reported solve (besides high CPU usage)? is this still relevant https://github.com/dynamoosejs/dynamoose/issues/458#issuecomment-440924690?

**Comment by fishcharlie** [comment]
@aecorredor You running v1 or v2? I'd love to chat more about this to help dig into it more. In the README of this repo there is a link to join our Slack room. If you could, I'd love it if you'd ping me on there and I can help further. These type of issues are best suited for more of a chat based environment.

**Comment by aecorredor** [comment]
@fishcharlie we're running v1 right now, haven't made the move to v2 since it's still in beta and we want to remain on the safe side for what we're doing. I'll join the slack and we can talk more there. Thanks for the fast reply!
