### ISSUE TITLE
Model.delete - Am I doing it correctly?

### ISSUE THREAD

**Issue by Kedarnag13** [dynamoosejs/dynamoose#532]
I'm facing an issue when using **Model.delete** with **condition**. What I'm trying to achieve is, I want to delete the record only if it exists, as the delete action is idempotent. So I used the **condition**, but it does not seem to have any impact, it never fails. Here is my code

```
Recommendation.delete({uuid: uuid}, {
    condition: 'attribute_exists(#id)',
    conditionNames: {'#id': 'uuid'},
    conditionValues: { ':uuid': uuid }
  }, (err) => {
    if (err) {
      console.log(err);
    }
    const response = {
      statusCode: 200,
      message: 'Recommendation deleted successfully!'
    }
    callback(null, response);
  });
```

The endpoint always returns -

```
{
    "statusCode": 200,
    "message": "Recommendation deleted successfully!"
}
```

**Comment by fishcharlie** [comment]
@Kedarnag13 Thanks for creating an issue! Before I get to your issue, I'd like to mention that the issue templates are required on this project. There is a lot of information included in that issue template that helps give us information about your issue. Not filling that out only makes my job harder. Please be sure to fill out the issue template next time instead of just replacing it with your own content.

Your code looks incorrect. Of course it will always return that. You have nothing in your code preventing that from occurring when there is an error. You log the error, but there is nothing to prevent it from returning that response (error or no error). Maybe adding an else statement and wrapping the response in that? Probably need to be sure that you call your callback in the error if part as well.

Kinda gets back to the issue template thing since there is a question about `I have read through the Dynamoose documentation before posting this issue`. In the [documentation](https://dynamoosejs.com/api#modeldeletekey-options-callback), it lists 2 valid options that you can pass into the options object. There is nothing to indicate it supports conditions.

If you look at the code, there is also no indication that your code is supported.

https://github.com/dynamoosejs/dynamoose/blob/0766c9285584ca42f1b18c7a7fdf5a9936a4d365/lib/Model.js#L1109-L1193

That being said. The condition you are looking to do is already supported in Dynamoose. So no need to even pass in an options object in your case, since Dynamoose will ensure it exists before trying to delete it.

https://github.com/dynamoosejs/dynamoose/blob/0766c9285584ca42f1b18c7a7fdf5a9936a4d365/lib/Model.js#L1152

As mentioned in the documentation as well, there is an `update` option. Which says:

> `update` (boolean): Will return the object deleted (default: false), if set to false and no object was deleted this function will fail silently.

It sounds like maybe that is what you are looking for.

If you think it'd be valuable to add more functionality to this feel free to create a PR!

Good luck!

**Comment by rahu2581** [comment]
Hi @fishcharlie,
I also faced this issue, but with a different check condition.
According to the AWS docs the ConditionExpression should be supported for PutItem, UpdateItem and DeleteItem.
My use-case is to prevent the deletion of an item by hashkey when the condition does not check out (Item belongs to a different user for example. Match on an additional non-key attribute.)

Otherwise I would have to read the item first before issuing a delete request. And of course this could lead to race conditions since its not an atomic operation.

Any chance to reopen this issue?

Please let me know if you need more information or if I should create a new issue for this using the template...

BR,
Rainer

**Comment by gregmsanderson** [comment]
Hi @fishcharlie 
Yep, I've just found the exact same issue @rahu2581 has detailed. I would like the delete to be conditional (e.g. include in the options a condition check to ensure it belongs to the user asking to delete it). _Without_ supporting conditional checks for Delete, someone could delete anything as long as they entered a valid hash ID.

I don't know if you have any plans to support it imminently? Else I guess the options are:
1) Read the item first and then delete it
2) Use the AWS SDK to delete it. It supports conditions on delete. But then the point of using Dynamoose was to avoid using the SDK
3) Can it be done with Dynamoose  transactions? I see they have a mention of conditionCheck so perhaps use that as a interim solution? I'm not clear how since I haven't used them.

Thanks!

**Comment by fishcharlie** [comment]
It looks like Dynamoose doesn’t support this currently. Feel free to create a PR.

**Comment by gregmsanderson** [comment]
Ok, no problem. For now I'll stick with (1) or (2) so don't worry :)

**Comment by dolsem** [comment]
@fishcharlie perhaps it's worth re-opening the issue or opening a new one with feature request label?
