### ISSUE TITLE
Model.transaction.conditionCheck doesn't resolve the key promise

### ISSUE THREAD

**Issue by alexpovh** [dynamoosejs/dynamoose#539]
### Summary:

`dynamoose.transaction([ModelTwo.create({ modelOneId: "123", sortKey: "456" }, ModelOne.transaction.conditionCheck({ id: "123" })])` sends empty key data to dynamodb:

```
{
  "TransactItems": [
    {
      "Put": {
        "TableName": "ModelTwo",
        "Item": {
          "modelOneId": {
            "S": "123"
          },
          "sortKey": {
            "S": "456"
          }
        },
        "ConditionExpression": "attribute_not_exists(modelOneId)"
      }
    },
    {
      "ConditionCheck": {
        "TableName": "ModelOne",
        "Key": {
          "id": {}
        },
        "ConditionExpression": "attribute_exists(id)"
      }
    }
  ],
  "ClientRequestToken": "<edited>"
}
```

This results in `ValidationException: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes`

#### Schema
```
    ModelOne: {
      id: {
        type: String,
        hashKey: true
      }
    }

    ModelTwo: {
      modelOneId: {
        type: String,
        hashKey: true
      },
      sortKey: {
        type: String,
        rangeKey: true
      }
    }
```

#### Model
```
Same as schema
```

#### General
```
// this doesn't work:
await dynamoose.transaction([
  ModelTwo.create({ modelOneId: "123", sortKey: "456" },
  ModelOne.transaction.conditionCheck({ id: "123" })
])

// this works!
const tx = [
  ModelTwo.create({ modelOneId: "123", sortKey: "456" },
  await ModelOne.transaction.conditionCheck({ id: "123" })
]
tx[1].ConditionCheck.Key.id = await tx[1].ConditionCheck.Key.id
await dynamoose.transaction(tx)
```

### Current output and behavior:

Transaction/ConditionCheck doesn't unbox the promise on the Key field.

### Expected output and behavior:

Transaction/ConditionCheck unboxes the promise on the Key field.

### Environment:

Operating System: OS X
Operating System Version: 10.14.2
Node.js version (`node -v`): v10.14.2
NPM version: (`npm -v`): 6.4.1
Dynamoose version: 1.4.0
Dynamoose Plugins: N/A
-

### Dynamoose Plugins:

- [ ] Yes, I believe that one or multiple 3rd party Dynamoose plugins are effecting this issue
- [ ] No, I believe this issue is independent of any 3rd party Dynamoose plugins I'm using
- [ ] Unknown, I'm unsure if Dynamoose plugins are effecting this issue
- [X] I am not using any Dynamoose plugins

### Type (select 1):
- [X] Bug report
- [ ] Feature suggestion
- [ ] Question
- [ ] Other suggestion
- [ ] Something not listed here

### Other:
- [X] I have read through the Dynamoose documentation before posting this issue
- [X] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [X] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [X] I have tested the code provided and am confident it doesn't work as intended
- [X] I have ensured that all of my plugins that I'm using with Dynamoose are listed above
- [X] I have filled out all fields above
- [X] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@alexpovh I'm finding a lot of bugs in your code. I'm closing this issue because of that.

One important note, a Dynamoose model, is not the same as a Dynamoose schema. And neither of your schemas or models included the Dynamoose code itself.

You are missing a `)` at the end of the create call. It should be [`ModelTwo.transaction.create`](https://dynamoosejs.com/api#modeltransaction).

```js
await dynamoose.transaction([
  ModelTwo.create({ modelOneId: "123", sortKey: "456" },
  ModelOne.transaction.conditionCheck({ id: "123" })
])
```

Same things here. You also will never need to await a `Model.transaction`. I also have no idea what `tx[1].ConditionCheck.Key.id = await tx[1].ConditionCheck.Key.id` is doing since I don't think `tx[1].ConditionCheck.Key.id` is a promise. But if you `console.log` that and post the result here, that would help, and I would **love** to see what the result of that is. There is a chance that there is maybe a bug where the `toDynamo` call we aren't awaiting on the backend. But I'd need more details about that in order to dig deeper. 

```js
const tx = [
  ModelTwo.create({ modelOneId: "123", sortKey: "456" },
  await ModelOne.transaction.conditionCheck({ id: "123" })
]
tx[1].ConditionCheck.Key.id = await tx[1].ConditionCheck.Key.id
await dynamoose.transaction(tx)
```

Finally and most importantly, your `[Model.transaction.conditionCheck](https://dynamoosejs.com/api#modeltransactionconditioncheckkey-options)` looks nothing like the documentation. So I'm not even sure if it's a valid conditionCheck. What exactly are you trying to do with that conditionCheck, what is the objective? I'd read up on the [AWS condition expression documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html).

---

I'd be more than happy to reopen this issue if you provide more information. I'm really looking for a full reproducible example that I can copy and paste into my text editor, run, and reproduce the issue instantly. And bug free haha.

But do me a favor and try some of the other tips I had above as well before resorting to this.

Something like the following is a great example of a code snippet that I can copy, paste, run, and use:

```js
const dynamoose = require('dynamoose');
dynamoose.AWS.config.update({
	"accessKeyId": "DEVELOPMENTID",
	"secretAccessKey": "DEVELOPMENTSECRET",
	"region": "us-west-2"
});
dynamoose.local();


const schema = new dynamoose.Schema({
	id: {
		type: String
	},
}, {timestamps: true});
const User = dynamoose.model('User', schema);

async function main() {
	await User.create({login: 'test@test.com'});
}
main();
```

As you can see it includes everything I need to test it out and reproduce the issue and nothing more. Of course yours will look different, and the above code is just an example.

**Comment by alexpovh** [comment]
@fishcharlie thank you for the quick feedback and apologies for the bugs in the code.

Here is a working example that reproduces the problem, please note that it needs to be executed against an aws dynamodb instance because local doesn't support transactions yet.

```
const dynamoose = require('dynamoose')

dynamoose.AWS.config.update({
    "region": "us-west-2"
})

const modelOneSchema = new dynamoose.Schema({
    id: {
        type: String,
        hashKey: true
    }
})

const modelTwoSchema = new dynamoose.Schema({
    modelOneId: {
        type: String,
        hashKey: true
    },
    sortKey: {
        type: String,
        rangeKey: true
    }
})

const ModelOne = dynamoose.model('ModelOne', modelOneSchema)
const ModelTwo = dynamoose.model('ModelTwo', modelTwoSchema)

async function main() {
    // create model one
    await ModelOne.create({ id: '123' }, { overwrite: true })

    // create model two only if model one exists
    const txData = [
        ModelTwo.transaction.create({ modelOneId: '123', sortKey: '345' }, { overwrite: true }),
        ModelOne.transaction.conditionCheck('123', { condition: 'attribute_exists(id)' } )
    ]

    console.log(`txData as is: ${JSON.stringify(txData, null, 2)}`)
    console.log(`txData with resolved promises: ${JSON.stringify([await txData[0], await txData[1]], null, 2)}`)

    try {
        await dynamoose.transaction(txData)
    } catch (err) {
        console.log(`Failed due to the empty key: ${err}`)
    }

    // Now we work around this issue by explicitly resolving key promise:
    console.log(`is txData[1] a Promise? ${txData[1] instanceof Promise ? 'Yes it is!' : 'No, it\'s not'}`)
    txData[1] = await txData[1]

    console.log(`is txData[1].ConditionCheck.Key.id a Promise? ${txData[1].ConditionCheck.Key.id instanceof Promise ? 'Yes it is!' : 'No, it\'s not'}`)
    txData[1].ConditionCheck.Key.id = await txData[1].ConditionCheck.Key.id

    await dynamoose.transaction(txData)
    console.log('Succeeds when key promise is resolved')
}

main()
```

Here is the output I'm getting:
```
AWS_PROFILE=axr-ppd node index.js 
txData as is: [
  {},
  {}
]
txData with resolved promises: [
  {
    "Put": {
      "TableName": "ModelTwo",
      "Item": {
        "modelOneId": {
          "S": "123"
        },
        "sortKey": {
          "S": "345"
        }
      }
    }
  },
  {
    "ConditionCheck": {
      "TableName": "ModelOne",
      "Key": {
        "id": {}
      },
      "ConditionExpression": "attribute_exists(id)"
    }
  }
]
Failed due to the empty key: ValidationException: Supplied AttributeValue is empty, must contain exactly one of the supported datatypes
is txData[1] a Promise? Yes it is!
is txData[1].ConditionCheck.Key.id a Promise? Yes it is!
Succeeds when key promise is resolved
```

My research shows that value returned by `ModelOne.transaction.conditionCheck({ id: '123' }, { condition: 'attribute_exists(id)' } )` is a Promise and its resolved value's property at `ConditionCheck.Key.id` path is also a Promise.

The use case I'm solving for here is to support creation of `ModelTwo` only when `ModelOne` (referenced by the `ModelTwo`'s `modelOneId` key) exists.

**Comment by fishcharlie** [comment]
@alexpovh So `dynamoose.transaction` should call `Promise.all` on the array passed in. So I'm still not sure I'm completely following.

https://github.com/dynamoosejs/dynamoose/blob/75f5f87ce34659deaed1f41e5c8c35cfa2125f41/lib/index.js#L239
