### ISSUE TITLE
Error while fetching Number attribute type with Null value

### ISSUE THREAD

**Issue by lintobrango** [dynamoosejs/dynamoose#589]
### Summary: Error while fetching Null attribute type in DynamoDB ("rating":{"NULL":true}) as Number attribute in schema.

Error : Attribute "rating" of type "N" has an invalid value of {"NULL":true}

#### Schema

const person = new Schema({
    sid: {
        type: Number,
        hashKey: true
    },
    asd: [
    {
        ID: Number,
        Activities : [
        {
            ....
            ....
            rating: {
                type:Number,
                required: false
            },
            startDate: String
        }
        ]
    }
    ]
});

#### Model
var personModel = dynamoose.model(config.schema.person, Person);
var personActivities = await personModel .scan('sid').eq(1).exec();

### Current output and behavior:

Attribute "rating" of type "N" has an invalid value of {"NULL":true}

### Expected output and behavior:

get rating as null

### Environment: dev

Operating System: windows
Operating System Version: 10
Node.js version (`node -v`):v8.14.0
NPM version: (`npm -v`):6.4.1
Dynamoose version:1.6.4
Dynamoose Plugins: 
https://www.npmjs.com/package/dynamoose
-

### Dynamoose Plugins:

- [ ] Yes, I believe that one or multiple 3rd party Dynamoose plugins are effecting this issue
- [ ] No, I believe this issue is independent of any 3rd party Dynamoose plugins I'm using
- [ ] Unknown, I'm unsure if Dynamoose plugins are effecting this issue
- [x] I am not using any Dynamoose plugins

### Type (select 1):
- [ ] Bug report
- [ ] Feature suggestion
- [x] Question
- [ ] Other suggestion
- [ ] Something not listed here

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [x] I have ensured that all of my plugins that I'm using with Dynamoose are listed above
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@lintobrango Sounds like you have bad data in your table. Make sure you don't have any records where you have `"rating":{"NULL":true}` in your table.

**Comment by hash-bang** [comment]
I've also run into this issue. So +1 on getting a fix.
Pretty sure the logic here should be that if `{required: false}` is set, to simply accept that the number is empty.

Best workaround for now is overriding parser with:

```javascript
{
  someField: {type: Number, fromDynamo: v => _.isEqual(v, {NULL: true}) ? {N: 0} : v},
}

```

**Comment by patrickgreenwell** [comment]
Thank you @hash-bang for your solution, I'm surprised there haven't been more issues like this crop up.  +1 on getting this fixed as well. At least you could implement something like the native Bool handler and allow for this to dump a null out when getting from dynamo. or allowing this in the schema by a `nullable:true` prop.

**Comment by fishcharlie** [comment]
I don’t see the point in changing this behavior. Null is a different type than Number. The whole purpose of Dynamoose is to enforce schemas for your DynamoDB objects.

What exactly is the use case here? Why not just store nothing for that property? What is the difference between null and storing nothing in this case? Or if you modify it upon receiving it, if you are setting it to 0, why not just set it to 0 in DynamoDB to begin with?

**Comment by patrickgreenwell** [comment]
1. Because nullable types exist(and not just for numbers, but strings too).
2. Because usage of this schema And library may not be the only thing that
has write access to this table or the use case is read access only.
3. You could be migrating to use a stronger schema and don’t want to have
to loop through every item in the table to convert nulls to a default
value. But do want to display those to a client upon read.

This is something explicitly supported by dynamo dB and the document client
(
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html
) as an attribute type.

If you want to not support it then you should at least call it out in
documentation.

The use of native booleans and the flag in dynamoose, which are stored in
dynamo in a nearly identical way, leads me to push for support for null
values too.

**Comment by fishcharlie** [comment]
I’m not opposed to adding null as a type to Dynamoose. But I’m trying to figure out real world use cases for it. As of right now I’d just add it as a type just like anything else and disallow using it in place of other defined types. Because I don’t see the practical use case for anything else. Which means the original issue of this issue would still exist.

What is the benefit of doing it over just not storing anything for that value? And what is the difference? If a value exists as null, vs an attribute in your schema that doesn’t exist in a specific item, what is the difference between those two situations from a practical standpoint? What are the differences in how they should be interpreted from a developers perspective?

The 2nd point I don’t see as being valid. You have to remain some type of control over the data. Dynamoose already throws errors for using the wrong type in your data. If you have other factors writing bad data to your database, you are gonna run into so many problems.

I need to understand more real world use cases in order to assess this.
