### ISSUE TITLE
Help on examples on using `.query` and the query object (not the chainable methods)

### ISSUE THREAD

**Issue by diosney** [dynamoosejs/dynamoose#615]
### Summary:

I'm trying to do a generic query builder that transforms URL queries to a REST API to the inner syntax that Dynamoose query object expects, and for now I was able to implement the sorting and the sparse fieldsets, but for some reason I cannot do the same with even simple queries using `filter, and, or`, and since there is little to none documentation or examples whatsoever on how to do it, I'm having a hard time making it to work, I even looked into the tests but all examples are related to the chainable methods, and the Query source code didn't helped me a lot too, so any help or guidance will be appreciated.

Note: I wanted to use the query options variant instead of the chainable methods since it would be easier for me to build and transform the API requests into the query options, and this is how in the past I've do it with some other ORMs like Sequelize, for instance.

https://dynamoosejs.com/api/query

Thanks

#### Schema
```
const schema: any = new orm.Schema({
      id       : {
        type    : String,
        hashKey : true,
        required: true,
        default : () => {
          return uuid.v4();
        }
      },
      type     : {
        type        : String,
        default     : 'user',
        forceDefault: true,
        index       : [
          {
            global    : true,
            name      : 'typeUsernameGlobalIndex',
            rangeKey  : 'username',
            project   : true,
            throughput: defaultThroughput
          },
          {
            global    : true,
            name      : 'typeCreatedAtGlobalIndex',
            rangeKey  : 'createdAt',
            project   : true,
            throughput: defaultThroughput
          }
        ]
      },
      username : {
        type    : String,
        required: true
      },
      createdAt: {
        type: String
      }
    }, Object.assign({}, ORM_SCHEMA_DEFAULT_OPTIONS, {
      throughput: defaultThroughput
    }));
```

#### Model
```
orm.model(process.env.SERVICE_DYNAMODB_TABLE_USERS, schema);
```

#### General

I'm calling the query method like the following:

```
users = await User
        .query(...filterQuery)
        .exec();
```
which `filterQuery` is an array with to items, the first is the `query` object and the second one the `options` object.

### Current output and behavior:

I've tried with a lot of `filterQuery` sets and variations foe example, filter by the `username` field, like (first array item is the query object, second one the options object, and I tried the filter on both maps without any results):

filterQuery [ { type: { eq: 'user' } }, { and: { filter: { username: eq: "some" } } } ]
filterQuery [ { type: { eq: 'user' } }, { { filter: { username: eq: "some" } } } ]
filterQuery [ { type: { eq: 'user' } }, { { username: { eq: "some" } } ]
filterQuery [ { type: { eq: 'user' } }, { { username: { filter: { eq: "some" } } } } ]
filterQuery [ { type: { eq: 'user' } }, { { username: { filter: { eq: "some" } } } } ]

And no matter how I build the query, the result is always the same, an unfiltered array with all users.

### Expected output and behavior:

That the filter works and return a filtered array.

### Environment:

Operating System: Kubuntu 
Operating System Version: 18.04 64bits
Node.js version (`node -v`): v10.0.0
NPM version: (`npm -v`): 6.9.0
Dynamoose version: 1.7.2
Dynamoose Plugins: none

### Dynamoose Plugins:

- [ ] Yes, I believe that one or multiple 3rd party Dynamoose plugins are effecting this issue
- [ ] No, I believe this issue is independent of any 3rd party Dynamoose plugins I'm using
- [ ] Unknown, I'm unsure if Dynamoose plugins are effecting this issue
- [x] I am not using any Dynamoose plugins

### Other information (if applicable):

None

### Type (select 1):
- [ ] Bug report
- [ ] Feature suggestion
- [x] Question
- [ ] Other suggestion
- [ ] Something not listed here

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [x] I have tested the code provided and am confident it doesn't work as intended
- [not applicable] I have ensured that all of my plugins that I'm using with Dynamoose are listed above
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by diosney** [comment]
@fishcharlie Any help on this would be awesome :)

**Comment by FHappy** [comment]
+1

**Comment by fishcharlie** [comment]
@diosney I apologize for the delay. I don't think this is possible with Dynamoose at the current time. You would have to do something like the following:

```js
users = await User.query("type").eq("user").where("username").eq("some").exec();
```

**Comment by diosney** [comment]
@fishcharlie Thanks, no problem, I found a way to build dynamically the chainable methods.

**Comment by uzochukwuonuegbu** [comment]
Hello @diosney , please can you let me know how you built the chainable methods, or a snippet would do. I'm having the same problem and I need your help.

**Comment by fishcharlie** [comment]
@uzochukwuonuegbu Your question isn't very clear about what you are trying to do. So I'm making a lot of assumptions here about what your data structure looks like, and what you are trying to do.

That being said, here is a quick example of using chainable methods.

```js
const obj = {"firstName": "Charlie", "lastName": "Fish"}; // This isn't the best example, but doing it here just to prove my point.

const objEntries = Object.entries(obj); // [["firstName", "Charlie"], ["lastName", "Fish"]]

// Method 1
let scan = User.scan();
for (let i = 0; i < objEntries.length; i++) {
    const [key, value] = objEntries; // key = "firstName" & value = "Charlie"
    scan = scan.where(key).eq(value);
}
const results = await scan.exec();

// Method 2
const results = await objEntries.reduce((scan, currentValue) => {
    const [key, value] = objEntries; // key = "firstName" & value = "Charlie"

    return scan.where(key).eq(value);
}, User.scan()).exec();
```

Now. The reason why `obj` isn't **totally** recommended, is the better way to do this would be:

```js
const obj = {"firstName": "Charlie", "lastName": "Fish"};
const results = await User.scan(obj);
```

However for complicated conditionals, that won't work. For example, see #932. But, I'm using it here to demonstrate how to do this.

Of course, you can scale up the complexity of `obj` and add more logic about how you want to handle it. Instead of just doing a `.where().eq()` you could expand that to use different methods, depending on whatever logic you want to set. You could have conditionals, or whatever. It can scale up and be as complicated as you want. But I think this demonstrates the basics of it.

The key things here:

1. **Every** chained method (except for `exec`, and maybe a few others I'm forgetting) returns the scan instance, so you can easily set the result of that chained method to a variable, and use it over and over.
2. Once you are done calling all of the chained methods, you can simply call `exec` on that variable and it'll handle as expected.
3. It's important to note that it's `scan = scan.where(key).eq(value);` **NOT** `scan.where(key).eq(value);`. The latter **might** work, but in my opinion is more risky and less clear what you are doing. I wouldn't be surprised if Dynamoose makes a change in the future that is not considered a breaking change that breaks the second version. So I wouldn't consider the non equals version to be reliable and stable. I'd use the non equals version at your own risk. However, the second method listed above, does the same thing due to how [`Array.reduce`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce) works.
4. This same concept applies to Condition, Scan, and Query. And honestly anything else that uses chainable methods in JavaScript.

After writing all of this I realized the original issue is about `query` not `scan`. I just used `scan` because I was thinking about it at the time. Not gonna go back and rewrite my answer tho since the same concepts apply to both.

I hope this helps answer your question! If you have any more questions or wanna provide more detail about what you are trying to do I can try to customize my example a bit more to what you are trying to achieve.

Thanks for using Dynamoose!

**Comment by diosney** [comment]
@uzochukwuonuegbu Sorry for being late, kind of bussy, you know how it is.

I did it for a generic Serverless JSON:API library I was working on, so expect the code to be kind of convoluted.

See this function at https://gitlab.com/vifros/serverless/serverless-json-api/-/blob/master/src/classes/jsonapi.class.ts#L382

There you are going to find how I built the queries step by step depending on the input entry, for instance:

```typescript
...
   // This is the initial setup for the query object.
   let query: any = model
      .query('type')
      .using(`type${uppercasedRangeKey}GlobalIndex`)
      .eq(type);

    // This is a complex function that builds the query depending on the input filter object, see below.
    if ('filter' in reqQuery) {
      buildQueryFromFilter(query, reqQuery.filter, schemaObject, rangeKey);
    }

    // This is how I queued the sorting.
    switch (reqQuery.sort[0]) {
      case '+':
        query.ascending();
        break;

      case '-':
        query.descending();
        break;

      default:
        query.ascending();
        break;
    }

...

    // How setup a limit.
    query.limit(pageSizeOptimizationForLists);

    // And pagination.
    if (reqQuery.page.after
        && reqQuery.page.after !== 'null') { // Due the base64 encoding.

      // TODO @diosney: Validate this.
      query.startAt(JSON.parse(Buffer.from(reqQuery.page.after, 'base64').toString()));
    }

...
   // And sparse fieldsets.
   query.attributes(fieldsToReturn);

...
```

And the `buildQueryFromFilter` function you can find it at https://gitlab.com/vifros/serverless/serverless-json-api/-/blob/master/src/classes/jsonapi.class.ts#L488

There you will see how I built the filters from an input object, I first do some checks and normalizations and later in the function I really use the `query` object again, starting with the last `if...else`:

```typescript
 if (fieldName === rangeKey) {
          query.where(rangeKey);

          if (hasNotOperator) {
            query.not()[operator.replace('$', '')](...operatorValue);
          }
          else {
            query[operator.replace('$', '')](...operatorValue);
          }
        }
        else {
          // index === 0 is when no `where` was added (no filter on rangeKey).
          // index === 1 is when a `where` was added (filter on rangeKey).
          //
          // On those cases, the `and` is not needed since it is already implicit.
          if (index >= 1 && !hasOrOperator) {
            query.and();
          }

          if (index > 0 && hasOrOperator) {
            query.or();
          }

          query.filter(fieldName);

          // This ugly repeated if-else is due `this` is lost if we cache the query.
          if (hasNotOperator) {
            if (operator === '$in') {
              query.not()[operator.replace('$', '')](operatorValue);
            }
            else {
              query.not()[operator.replace('$', '')](...operatorValue);
            }
          }
          else {
            if (operator === '$in') {
              query[operator.replace('$', '')](operatorValue);
            }
            else {
              query[operator.replace('$', '')](...operatorValue);
            }
          }
        }
```

Hope this helps you a little bit, I only spent a month or two doing the library for a project and then moved on.
