### ISSUE TITLE
Once again - finally Object vs String

### ISSUE THREAD

**Issue by bart** [dynamoosejs/dynamoose#649]
Hey everyone,

first of all I want to thank you for the huge amount of effort you've put into this package. Looks very neat. I'm struggling with the data attributes of my model. Object type gets converted to String which results in an error. Or in other words: When I try to store an object that contain arrays dynamoose reads and writes it as string values instead of a map. Any explanation for it? I searched for this issue here already and found some discussion about it but no solution. So maybe we can finish this entire topic here and find a solution?

**Comment by fishcharlie** [comment]
@bart When you first create an issue the first line says `Not filling out ALL of the relevant fields in this issue will cause your issue to be closed`.

I'm closing this issue. Please help us help you by following our process so that we don't waste time going back and forth about the important details regarding issues on GitHub.

**Comment by bart** [comment]
But sometimes it just makes no sense. Just wanted to help. I'll use `@aws/dynamodb-data-mapper` which works as expected. Cheers
