### ISSUE TITLE
How to do OR statements??? Docs are completely empty unfortunately

### ISSUE THREAD

**Issue by cupcakearmy** [dynamoosejs/dynamoose#707]
### Summary:

How to use the `.or()` statement?
I've also checked the mongoose docs

### Code sample:

```typescript
query('ownerId').eq(a).or().eq(b)

query('ownerId').eq(a).or({ownerId: a}).or({ownerId: b})
```

### Current output and behavior:

```
Invalid Query state: %s must follow query(), where() or filter()
```

### Expected output and behavior:

Be able to or the query

### Environment:

Operating System:
Operating System Version:
Node.js version (`node -v`):
NPM version: (`npm -v`):
Dynamoose version: 1.11.1

### Type (select 1):
- [ ] Bug report
- [ ] Feature suggestion
- [x] Question
- [ ] Other suggestion
- [ ] Something not listed here

### Other:
- [x] I have read through the Dynamoose documentation before posting this issue
- [x] I have searched through the GitHub issues (including closed issues) and pull requests to ensure this issue has not already been raised before
- [x] I have searched the internet and Stack Overflow to ensure this issue hasn't been raised or answered before
- [ ] I have tested the code provided and am confident it doesn't work as intended
- [ ] I have ensured that all of my plugins that I'm using with Dynamoose are listed above
- [x] I have filled out all fields above
- [x] I am running the latest version of Dynamoose

**Comment by fishcharlie** [comment]
@cupcakearmy Check out `query.in`. The documentation is sadly one of the biggest struggles for the project. In the v2.0 rewrite, the documentation is all new. I'm pretty confident `query.in` works almost the same in the v2.0 rewrite as v1.x. So you can look at the documentation in PR #677 `docs/api/Query.md` lines 167-173.

**Comment by cupcakearmy** [comment]
Thanks for the very quick response!
Awesome to see that the docs are being addressed :)

So i guess it's my fault. I was using `.or()` but I was searching for `.in()` then. Apparently `.or` is only for filters right?

But I'm still not able to get this to work. I've looked at the docs you have suggested (https://github.com/dynamoosejs/dynamoose/pull/677/files#diff-db52ce5221625ccc50b7c02cddf52d97R167-R172)

```typescript
SomeModel.query('ownerId').in(memberIds).exec()
```
Yields a
```
{
    "name": "QueryError",
    "message": "Invalid Query state: eq must follow query()"
}
```

Thanks for the help!

**Comment by cupcakearmy** [comment]
Looks like I solved it.

My error was that was using the `query` and not `scan` builder.

basically changing

```typescript
SomeModel.query('ownerId').in(memberIds).exec()
```

to

```typescript
SomeModel.scan('ownerId').in(memberIds).exec()
```

**Comment by fishcharlie** [comment]
@cupcakearmy

> Looks like I solved it.
> 
> My error was that was using the `query` and not `scan` builder.
> 
> basically changing
> 
> ```ts
> SomeModel.query('ownerId').in(memberIds).exec() // Nope
> ```
> 
> to
> 
> ```ts
> SomeModel.scan('ownerId').in(memberIds).exec() // Yaas
> ```

Couple things here. It's highly discouraged to do Scan's in DynamoDB, since it has to search through every document you have. At scale this is not good in terms of performance at all. Of course, you did run into the big requirement about Query's, you must query for where the hashKey = something. You can't do an `OR` for that hashKey without doing multiple Query's.

Without knowing more about your data structure I can't really help give any suggestions for how to restructure your data. But chances are you might want to change your data structure so the performance is better.

---

On a side note. The reason I'm replying to this closed issue is that in Dynamoose v2, I just added support for `OR` statements to Scan, Query & Conditionals along with groups. However if you want to keep using Scan, using `in` is probably the easiest for your use case.

However, as I said above, I'd consider rethinking how you think about your data. Checkout this video for more info on that: https://youtu.be/DIQVJqiSUkE.

**Comment by cupcakearmy** [comment]
Thanks for the response. Switched to Google cloud though and I will never go back to crap AWS xD
