### ISSUE TITLE
Schema: Separate defining keys and indexes from attributes

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#795]
I am still kind of concerned about setting the hashKey, rangeKey and indexes in a Schema and then using them in query. Currently it is very confusing and loose, especially when working with local indexes and secondary indexes. I think setting them should be more clear and separate from the attributes, e.g.

Currently you have to do it like so:

```
export const SpectatorSchema: SchemaAttributes = new Schema({
    customerId: {
        type: String,
        // Global secondary index
        index: {
            global: true,
            rangeKey: 'status',
        }
    },
    orderId: {
        type: String,
        hashKey: true,
        index: {
            rangeKey: 'status', // Local secondary index
        },
    },
    status: String,
    priceTotal: Number,
})
```

Here is a proposal to do it nice and clean: `new dynamoose.Schema(attributes, keys, [, options])`

Example:
```
new Schema({
   customerId: String
   orderId: String,
   status: String
   priceTotal: Number,
},
{
   hashKey: 'customerId',
   rangeKey: 'orderId',
   localIndexes: [
       {
          rangeKey: 'status',
          // More optional settings
       },
   ],
   globalIndexes: [{
      hashKey: 'orderId',
      // More optional settings
   }]
})
```

This is way it would be more humanly readable. Also it is clear that:

- A table requires to have at least a hashKey
- A table optionally can have a rangeKey
- A table can have only one hashKey and one rangeKey
- A table can define multiple local secondary indexes which have the same hashKey as the table but a different rangeKey
- A table can define global secondary indexes which have a different hashKey than the table and optionally a rangeKey

With this new definition this conditions are easy to describe in the documentation and easy to test. Currently it is all mixed up and kind of loose IMO. The defined keys can be used more clearly when using operations like getItem oder query and be tested. E.g. a query requires at least a hashKey and can optionally have a rangeKey.

Then operations might be refactored to be more clear also: E.g. a query requires at least a hashKey and then optionally a rangeKey or a key defined as a local index OR a hashKey from a global index with a rangeKey from the same global index:

Before: `Model.get(hashKey[, settings][, callback])`
After: `Model.get(keys[, settings][, callback])`

Example:
```
Order.get({
  hashKey: 1,
  sortKey: 2
});
```

See also https://github.com/dynamoosejs/dynamoose/issues/787

**Comment by fishcharlie** [comment]
Closing this. I wanted to rethink this for v2, especially with the feature idea to allow nested schemas, since nested properties can't have indexes. I think it'd be much cleaner to have this be part of the model.

I don't think this is gonna happen for v2 tho. If someone wants to submit a PR, I might reconsider this. But much higher priorities to take care of for the project right now IMO.

**Comment by MickL** [comment]
If this is going to be changed, it is a breaking change and should happen with v2. After working with Dynamoose IMO separating and clearifying they key and index definitions (this issue) and the query (787) should be on highest priority. It is really confusing, if not to say a mess. Everything is so lose with the overloading of functions and the current syntax that I pointed out in both issues does not make the work with DynamoDB clear. Setting the keys and indexes, and querying for them efficiently might be the most important part of DynamoDB modeling to be done right. And this is what the library should be all about or no?

Anyway I dont have the time to make PRs, it took me a while to make this proposal already and update the documenation, which hasnt been merged yet. And if I do so, i wouldnt even be safe that it gets merged or not.

I am considering switching to another library or just using aws-sdk.

**Comment by MickL** [comment]
This library does exactly what I proposed in the two issues: https://github.com/baseprime/dynamodb

**Comment by fishcharlie** [comment]
> it is a breaking change

Correct

> should happen with v2

Why not v3 or in the future? v2 had a **very** specific purpose with v2. The breaking changes in v2 were all very intentional and had a clear purpose. I did not make any breaking changes for the sake of making breaking changes. The goal was to rewrite the library to support a better foundation, and to cause as few breaking changes as possible. Keep in mind, that is not an easy feat at all.

> Everything is so lose with the overloading of functions and the current syntax that I pointed out in both issues does not make the work with DynamoDB clear.

I'd just like to point out, you are the very first person to complain about overloading of functions. **Very** first. I think that energy and time spent could be focused on much more valuable tasks. Overloading gives options. Pick which makes sense or works best in your use case, and go with it. You aren't going to agree with every decision every library makes. But I can think of use cases for each overload in Dynamoose. I'd suggest focusing on building your project or taking advantage of Dynamoose as opposed to complaining about the flexibility Dynamoose provides.

> Setting the keys and indexes, and querying for them efficiently might be the most important part of DynamoDB modeling to be done right.

Totally agree. Dynamoose provides very good support for this. It does everything you need it to. You can add indexes, set the keys, and query them efficiently. Just because the syntax doesn't match up with your vision for how it should be, doesn't mean it's not `done right`. And again, this is the first complaint I've heard about indexes or querying. If this gets traction and more support, that would be different. But I haven't heard any other complaints about this. Not gonna make major breaking changes just because of one complaint about the syntax.

It's also **VERY** important to remember that this library is based on and inspired by Mongoose. Dynamoose handles indexes almost identically to Mongoose (https://mongoosejs.com/docs/guide.html#indexes).

If you want to submit an issue to add support for a `schema.index` method so you can define them separately from the attributes. That is totally acceptable. However that would not be a breaking change. And would align with the way Mongoose does it.

If you don't like the way Mongoose syntax works, that is fine. But then this library isn't for you. But, I think this library communicates **extremely** well that it's inspired by Mongoose. That shouldn't come as a surprise to anyone.

There honestly shouldn't even be conversation about purposefully making a **breaking change** to divert away from the way Mongoose does it, when the current behavior works, and is aligned very well with Mongoose. And it also works and does everything you need it to do with DynamoDB. There is no problem or issue here. It aligns with the goals of the project exactly.

> Anyway I dont have the time to make PRs
> which hasnt been merged yet

Same reason as you. I don't work on Dynamoose 24/7. This is open source. Any time I work on it is time I'm volunteering and not getting paid for at all. If you don't like it, use your fork or something else. The reality is this project is very successful. And a lot of people rely and appreciate the work being done on this project. I'm sorry that it doesn't work for your use cases. Doesn't mean it's a bad project tho.

---

Just for the sake of full transparency to the rest of the community. I deleted the last comment by @MickL due to the fact that it was very off topic and not related to Dynamoose at all. I do not support people coming onto extremely established projects, complaining about established practices, not actually contributing any code and only complaining, then deciding to link to/advertise/discuss other open source projects.

Discussing or advertising other open source projects is considered off topic here. This is the Dynamoose repository, not any other repository. Let's keep the focus on Dynamoose 😃
