### ISSUE TITLE
`.query()` is not working

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#796]
`Cat.query("breed").contains("Terrier").exec()` will error: 
> Index can't be found for query.

@fishcharlie wrote:
> Dynamoose currently requires an index, but DynamoDB does not require an index when querying

I can confirm it works when I add an index to the schema, even tho I dont query for the index. But if I add an additional condition the same error occurs.

**Comment by jdrydn** [comment]
From what I can tell, this has fixed `eq` but not `in`:

```
Cat.query({ breed: { in: [ 'Terrier' ] } }).exec()
```

> InvalidParameter: Index can't be found for query.

Happy to dig into this further, right now I'm using `model.scan` instead of `model.query` 🤷‍♂️

**Comment by fishcharlie** [comment]
@jdrydn It's not possible to query a hashKey using `in`. You must query where `hashKey = ______`. Either using the table hashKey or an index hashKey. There is no way for Dynamoose to workaround that.

**Comment by arizonatribe** [comment]
@jdrydn What is the solution to run a query on dynamo rows whose hashkey matches one of multiple values? Would we really have to run multiple queries for every value in a list? Of course it's not a SQL database but there must be some way to express this kind of condition in a single Dynamo query.

**Comment by jdrydn** [comment]
@arizonatribe Check out “[Working with DynamoDB Queries](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html#Query.KeyConditionExpressions)” for more detail, but I’m afraid there’s no logic for `hashKey IN ?` or `hashKey = ? OR hashKey = ?`. If your table **is not** using range keys then you’d be able to use [`BatchGetItem`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html) to fetch multiple items in one operation, but AFAIK it’s a design/structural decision in DynamoDB so there’s no solution here.

**Comment by arizonatribe** [comment]
Turns out this wasn't a hashkey issued on my end after all. However when I refactored my code to do something like this:

```
const results = await model
  .query("fieldName")
  .eq("one")
  .or()
  .where("fieldName")
  .eq("two")
  .exec()
 ```
 
 It breaks in a rather cryptic way: `Cannot read property '0' of undefined`, tracing to [this line](https://github.com/dynamoose/dynamoose/blob/master/lib/DocumentRetriever.ts#L178) in the `DocumentRetriever.ts`.
 
 ```
res[myItem[0]] = {"type": myItem[1].type};
```
It seems that section of the code where the `comparisonChart` is built is not prepared for the `Symbol("OR")` amongst the other conditional objects.

Do you have confidence that the fluent chaining with `.or()` works (are there tests for it) or is this a known issue?
